# Generated by Django 4.2.2 on 2023-06-13 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('message_body', models.TextField(max_length=2000, verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Periodicty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_name', models.CharField(max_length=16, verbose_name='Периодичность')),
            ],
        ),
        migrations.CreateModel(
            name='SendingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=16, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='SendingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_time', models.TimeField(verbose_name='Время рассылки')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.client', verbose_name='Клиент')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.message', verbose_name='Сообщение')),
                ('periodicity_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.periodicty', verbose_name='Периодичность')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.sendingstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SendingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(auto_now=True, verbose_name='Время попытки')),
                ('attempt_status', models.BooleanField(verbose_name='Статус попытки')),
                ('server_response', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ответ сервера')),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sendingstatus', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
                'ordering': ('id',),
            },
        ),
    ]
